<h1>WHAT IS A TENSOR?</h1>

<div>A generalization of vector and matrices to potentially higher dimensions. Internally, TensorFlow represents tensorsas n-dimensional arrays if base datatypes.</div>
<br>
<div>
Each tensor has a data type and a shape
<br>
<h4>Data types:</h4>float32,int32,string,etc..
<h4>Shape:</h4>Represents the dimension of the data.
</div>

<h1>Creating tensors</h1>

In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from 'c:\\Users\\vigne\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>


EXAMPLES FOR TENSORS

In [2]:
string = tf.Variable("this is a string", tf.string)
integer = tf.Variable(512,tf.int16)
floating = tf.Variable(3.14874654,tf.float64)

<h1>RANK/DEGREE OF TENSORS</h1>
They denote the number of dimensions involved in the tensor. Tensor with rank 0 is known as a scalar.

<h2>CREATING TENSORS OF HIGHER RANKS</h2>

In [3]:
rank_1_tensor = tf.Variable(["test",'yes'], tf.string)
rank_2_tensor = tf.Variable([["test","ok"],["test","yes"]], tf.string)

<h3>To determine the rank of the tensor we call the tf.rank(tensor_object)</h3>

In [4]:
tf.rank(rank_2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
tf.rank(rank_1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

<h3>Shape of Tensors</h3>

<div>
The number of elements that are present in each dimension of the tensor object.<br>
To find the shape of a TensorFlow object, we use the object.shape.
</div>

In [7]:
rank_2_tensor.shape

TensorShape([2, 2])

In [9]:
rank_1_tensor.shape

TensorShape([2])

<h3>Changing the Shape</h3>
<div>
We cna modify the shape of a tensor flow object by using the reshape function.
</div>

In [16]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2,[3,-1])

In [13]:
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [14]:
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [17]:
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

<h2>TYPES OF TENSORS</h2>
<div>
<ul>
<li>Variable</li>
<li>Constant</li>
<li>Placeholder</li>
<li>SparseTensor</li>
</ul>
</div>

<h3>SOME EXAMPLES</h3>

<p>RESHAPING A ZERO TENSOR</p>

In [20]:
tensor_zeros = tf.zeros([4,4,4,4])
print(tensor_zeros)
new_tensor = tf.reshape(tensor_zeros,[64,-1])
print(new_tensor)

tf.Tensor(
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [